### PR TITLE
Updating Db code

### PR DESCRIPTION
**Pull request by Samuel-BF**
Hello,

I'm working on database code of Atk, which is quite old. The goals are: 

 - Simplicity : have less code : 
   - [x] rely on abstractions provided by PDO
   - [x] merge all *Query classes to only one
 - Compatibility : 
   - [x] make postgresql driver work again
   - [x] introduce a sqlite driver.
 - Security : 
    - [x] provide functions that help to use prepared statements in Query class
    - [x] make the prepared statements the default for all operations.
 - [x] Internationalization : allow all UTF-8 chars (except null character) in SQL identifiers such as table and column names (wich would prevent the need to use languages files for single-language application).

First step, published here (for master branch), is to move to more uniform database handling through PDO. It also :

- Removes Db Statement classes (replaced by PDOStatement).
- Removed some unused functions out of Db class (see doc/CHANGES for a full list), not
- Forces Mysql driver to ANSI mode, which makes SQL statements more compatible between Mysql and other drivers (notably : identifiers are escaped with double-quotes and not backticks anymore).

Note that i kept the *Ddl class (which aims to build CREATE TABLE queries), but untested as I don't see what is their utility in ATK framework. I suggest we remove them completely, unless someone sees an interest.

This commit works as well as master branch against [testsuite](https://framagit.org/samuelbf/atk-testsuite/), but this testsuite is not comprehensive, so i would ask for help to identify regressions.

### CODE REVIEW

**Comment by dangamba** [comment]
Hello,
thanks for your many contributions!
We've been very busy lately, but we promise we'll check them out asap.
BTW, what kind of project did you use ATK for? Just curious... :)

Cheers,
Daniele

**Comment by Samuel-BF** [comment]
Thanks for the news !


> BTW, what kind of project did you use ATK for? Just curious... :)

A very simple database project for a local NGO where I volunteer. What I find very powerful in ATK is it's very concise declarative syntax : just translate your database structure to Nodes/Attributes objects and you have a full-featured database edition software (with authentication, input validation, relations enforcement, ...).

But I encountered some serious security issues right after i've coded my little app, so I tried to correct them. And trying to secure the framework made me realize that some architectural shifts needs to be made first.

**Comment by Samuel-BF** [comment]
I accidentally merged the last two commits into one. So the title and description of 7a0d357 correspond only to a (small) part of the move. More important things in this commit were :

- Removal of ability to have several tables in a *Query object (this possibility was not used, in fact, and implied some complex and MySQL-specific code)
- Removal of soundex searches (were MySQL-only)
- Addition of regex searches for PostgreSQL and moving the code for regexes out of *Query class and into *Db classes
- Removed a hacky thing in MySQL about "int" values '' transformed to '0' (i did not succeed to corner a use case, my tests suggest that it would be in fact more useful for postgresql and this problem should disappear anyway with parametrized queries) -> this led to code de-duplication
- With all this code de-duplication, merged *Query classes into only one Query class, that will work fore every driver (remaining differences in search functions are moved to *Db class).

What should come next : 
- using QueryParts everywhere in Query and Db class
- using QueryParts everywhere else in ATK
- adding SQLite driver (the metadata can be retrieved with pragma functions)

**Comment by Samuel-BF** [comment]
Hello,

The work is almost done, now. I need help/advice for few questions : 

- I will remove *Ddl parts (which build queries like "CREATE VIEW", "DROP SEQUENCE" ,...), as imho it has nothing to do in ATK (ATK handles and modify data in database, but not table structures). Is it OK ?
- Is it possible to merge #44 to master, because i need to modify TreeNode.php, already modified by #44 and there will be a conflict if I do this independently (note : I could directly merge #44 in #41, but I let you decide !)
- DataNode and FileEditor doesn't work with current version of ATK (either 9.0 or master), and changes introduced by this PR make the path to repairing these features a bit longer. Would it be possible, at least for FileEditor, to integrate the patch proposed in #33 before i finish this PR, so I can ensure that it still work ?
- And, of course, these changes need to be tested with more code to check for regressions (i'm pretty sure there will be a lot of regressions, [testsuite](https://framagit.org/samuelbf/atk-testsuite) is far from being comprehensive).

What still need to be done : there remains some small pieces that I will move to QueryParts (but no complex one I think), the UTF-8 part is not working yet (but it is not the most important thing) and the doc/CHANGES will be rewritten to highlight important changes.

Thanks for your feedback!

**Comment by Samuel-BF** [comment]
That's it. Apart from small changes that will be needed once #44 is merged, I consider the PR ready.

There may remain some bugs, don't hesitate to show examples if you find out some.

Note that it introduces some potentially breaking changes that I've put highlighted in the beginning of doc/CHANGES. It also contains a fairly comprehensive list of modifications i made : if some point is unclear, ask me. My commit comments also contains information about how/why i did the modifications.

And I insist that these changes are quite important for security reasons. So integrate in the code you use in production asap.

**Comment by Samuel-BF** [comment]
Hello. Is someone working on it ?

If I get no news within 2-3 weeks, I may release examples of flaws I found as part as [ATK testsuite](https://framagit.org/samuelbf/atk-testsuite). For the moment, I identified 4 serious flaws related to DB code (all these flaws are fixed by db-rework branch).

**Comment by Samuel-BF** [comment]
I published [prototypes of the flaws](https://framagit.org/samuelbf/atk-testsuite/blob/security/tests/SQLInjectionTest.php). Note that [a discussion](https://github.com/atkphpframework/achievo/issues/17) highlighted some of these flaws nearly 5 years ago, referring to [an alert](https://www.netsparker.com/web-applications-advisories/xss-lfi-and-sql-injection-vulnerabilities-in-achievo/) publicly released in 2012.

**Pull request merged**
