### PR TITLE
Fixing UTF-8 language files

### PR DESCRIPTION
**Pull request by Samuel-BF**
During the import from [atkphpframework repository](https://github.com/atkphpframework/atk/blob/develop/languages), non-ascii characters where lost for non-UTF8 encoded language files (turkish, japanese, french, catalan, ...).

This pull request uses original strings from atkphpframework repository, re-encoded in UTF-8, to re-enable these languages in ATK.

### CODE REVIEW

**Comment by Samuel-BF** [comment]
Well, i added two commits : 
- the first is to improve french translations.
- the second removes ~20% of the translation files, strings that I have not found anywhere else in the source code. I guess they are no more used, but I may have missed some code paths that lead to using these strings (I searched for lines containing both the string and the "atktext" word before removing them).

**Review by dangamba — APPROVED** [review]

**Review by dangamba — APPROVED** [review]

**Review by dangamba — APPROVED** [review]

**Review by dangamba — COMMENTED** [review]
Hi Samuel, can you please elaborate on the method you used to select the lines to be removed?

**Comment by Samuel-BF** [comment]
I ran 'grep' across the source code with the strings.


There's (at least) one error : i deleted the 'feedback' strings while they are in fact used.

**Comment by Samuel-BF** [comment]
I reverted the deletion of translation strings, as some of them were in fact useful.

**Comment by Samuel-BF** [comment]
It was already merged into my-atk branch, [merged 3 days ago](https://github.com/Sintattica/atk/commit/dec1cb4b2f966174633e389408e54f31c7e91b7d).

**Pull request closed without merging**
